### ISSUE TITLE
Jigsaw returned code 4 when running the jigsaw driver to create a new mesh

### ISSUE THREAD

**Issue by melissamattwig** [noaa-ocs-modeling/OCSMesh#123]
Hello!

I ran into a jigsaw return code 4 when using the .run() function on the ocsmesh jigsaw driver object. 

`Traceback (most recent call last):
  File "/mnt/projects/hpc/mattwig/grid/ocsmesh/test_shapefile_genesee.py", line 214, in <module>
    mesh_s1 = driver_s1.run()
              ^^^^^^^^^^^^^^^
  File "/home/mattwig/miniconda3/envs/ocsmesh/lib/python3.11/site-packages/ocsmesh/driver.py", line 101, in run
    libsaw.jigsaw(
  File "/home/mattwig/miniconda3/envs/ocsmesh/lib/python3.11/site-packages/jigsawpy/libsaw.py", line 746, in jigsaw
    raise Exception(
Exception: JIGSAW returned code: 4`

For context, this is a .2dm mesh over the entirety of Lake Ontario including the floodplain. I was able to successfully remesh a significantly smaller area around a single river going into Lake Ontario using shapefiles from the NWM and a .2dm mesh around the river of interest that is a subset of the original larger .2dm mesh for the hfun. When I tried to then just replace the smaller .2dm mesh with the whole grid mesh for the hfun, I get this error when trying to run the driver. 

Originally when I started testing out ocsmesh on the whole grid I was getting a jigsaw error code 6, but after reading #68 I changed the values so non of them were negative anymore then got this error code 4. I'm not sure what it is about the whole lake/floodplain grid that causes this issue that is not an issue when using a subsetted mesh. I am using the same area for the domain for both the large lake mesh and the subsetted mesh. The domain is around the river of interest and is about the same size as the subsetted mesh and the shapefile I'm using to add as a feature to the hfun is within the domain size. I'm not sure if the issue could be related to using a small domain on a significantly larger hfun, but I didn't think this would be an issue since it is useful when remeshing locally.

Overall I'm a bit befuddled. Please let me know if more information is needed to solve this issue!

**Comment by SorooshMani-NOAA** [comment]
Hi @melissamattwig would it be possible for you to share a version of your meshing script? The code `6` from jigsaw means [wrong argument](https://github.com/dengwirda/jigsaw/blob/f99d8f4fe375210c1fa442d87ab60b494ab95662/inc/jigsaw_const.h#L62C16-L62C39), but solely based on that I cannot say what is causing the error. So I'd like to take a look at your script to see if anything stands out.

**Comment by melissamattwig** [comment]
Interesting that it's an invalid argument when the same code works for a smaller chunk of the mesh. Here is the meshing script (I did not include importing modules or the plotting calls since those are all derivations of the tutorial code you have). Please let me know if you need any more information and thank you for your help!!

```
## read in shapefile box around genesee river and confirm type is a geopandas dataframe
genesee_path = 'data/genesee.shp'
genesee = gpd.read_file(genesee_path)

## make genesee bounding box into ocsmesh domain (unary.union returns a geometry with the union of all geometries in gpd dataframe)
genesee_domain = ocsmesh.Geom(genesee.unary_union, crs=genesee.crs)

## size function, read in USACE floodplain mesh
## whole grid mesh
#size_function_mesh = ocsmesh.Mesh.open('o4-v01-0m_igld85_ocsmesh.2dm', crs=4326)

## genesee river chunk subsetted from whole grid
size_function_mesh = ocsmesh.Mesh.open('gen_subdmn.2dm', crs=4326)

## test to fix jigsaw error 4 by making a domain that maintains element lines along border of smaller mesh instead of
## just using an arbitrary box around the genesee river, DID NOT fix issue, but keeping use of geom_poly as domain instead 
## of genesee_polygons for rest of the code
mesh_obj = ocsmesh.Mesh.open('gen_subdmn.2dm', crs=4326)
geom_obj = ocsmesh.Geom(mesh_obj)
geom_poly = geom_obj.get_multipolygon()


## plot domain and mesh object before becoming actual size function, zoomed and whole grid
genesee_polygons = genesee_domain.get_multipolygon()
# geom_poly_m1 = geom_poly_1.intersection(roi_box)

## turn mesh into ocsmesh size function, check hmin and hmax so it is non-negative
hfun = ocsmesh.Hfun(size_function_mesh)

## transpose hfun
hfun_msh_t = hfun.msh_t()

## the output from the Hfun function is always in a projected crs while the input is usually in a geographic crs

## plotting element edge size of the mesh
hfun_2 = deepcopy(hfun) # copy to avoid modifying previous objects
hfun_2.size_from_mesh()

hfun_msh_t_2 = hfun_2.msh_t()

print('ADDING RIVERS')
rivers_size_function = ocsmesh.Hfun(ocsmesh.Mesh(deepcopy(hfun_msh_t)))
nwm_shp = 'data/ont.shp'
gdf_nwm_rivers = gpd.read_file(nwm_shp, layer=0, crs=4326)
rivers = (gdf_nwm_rivers.unary_union).intersection(geom_poly)

rivers_size_function.add_feature(gpd.GeoSeries(rivers,crs=4326).to_crs(hfun_msh_t.crs).unary_union, target_size=40, expansion_rate=0.005, nprocs=1)

river_size_function_t = rivers_size_function.msh_t()

## make jigsaw driver that will be meshed
genesee_driver_domain = ocsmesh.Geom(geom_poly, crs=4326)

print('MESHING')
driver_s1 = ocsmesh.JigsawDriver(genesee_driver_domain, rivers_size_function)
mesh_s1 = driver_s1.run()
```

**Comment by SorooshMani-NOAA** [comment]
@melissamattwig is `gen_subdmn.2dm` a file with mesh size values or is it a mesh with bathymetry values but you want to use the mesh elements as a guide for sizing of your OCSMesh driver?

If it's the latter, then you need to use your `hfun_msh_t_2` for creating the `rivers_size_function` size function object.

Please let me know if this helps.

**Comment by melissamattwig** [comment]
Using the `hfun_msh_t_2` worked! The code above worked when using `gen_subdmn.2dm` as the size function mesh, but was throwing me that error when I was using `o4-v01-0m_igld85_ocsmesh.2dm` which covered the entirety of Lake Ontario (the `gen_subdmn.2dm` file is a mesh around the Genesee River going into Lake Ontario). Now it works when using the o4-v01-0m_igld85_ocsmesh.2dm` file for the size function. If I am understanding correctly, the `size_from_mesh()` function gets mesh element sizes for the size function from the existing mesh elements for the OCSMesh driver?

Also, is it possible to interpolate depth information from the original mesh? In the pdf manual it looks like most of the depth interpolation is only using rasters.

**Comment by SorooshMani-NOAA** [comment]
Great! I'm glad that it work! For interpolating mesh to mesh you can use:
 https://github.com/noaa-ocs-modeling/OCSMesh/blob/d3b23f5473c69b68e32ce3466a84fee6ecafea1a/ocsmesh/utils.py#L1217

It takes `jigsawpy.msh_t` object as both source and target.

**Comment by melissamattwig** [comment]
Thank you!

I tried interpolating by adding this line of code after running the jigsaw driver

`mesh_s1.interpolate(hfun_msh_t_2)`

and it gave me a TypeError

```
Traceback (most recent call last):
  File "/mnt/projects/hpc/mattwig/grid/ocsmesh/test_shapefile_genesee.py", line 223, in <module>
    mesh_s1.interpolate(hfun_msh_t_2)
  File "/home/mattwig/miniconda3/envs/ocsmesh/lib/python3.11/site-packages/ocsmesh/mesh/mesh.py", line 386, in interpolate
    [(self.vert2['coord'], self.crs,
TypeError: 'jigsaw_msh_t' object is not iterable
```

Am I missing an argument? In the pdf manual the example passes in just the list of rasters. What is it about the mesh_t that needs to be iterable?

**Comment by SorooshMani-NOAA** [comment]
Currently the mesh object API only accepts raster inputs, the function I'm suggesting is a helper function from the `util` module. So you need to do something like:
```python
ocsmesh.utils(mesh_s1, hfun_msh_t_2)
```

**Comment by melissamattwig** [comment]
I think I'm getting hung up on the syntax around this function. 

When I added `ocsmesh.utils(mesh_s1, hfun_msh_t_2)`, I got `TypeError: 'module' object is not callable`. 

So then I added `from ocsmesh.utils import interpolate` to the modules I am loading in and then ran `interpolate(mesh_s1, hfun_msh_t_2)` and now it's giving me this error: `AttributeError: 'EuclideanMesh2D' object has no attribute 'mshID'`

**Comment by SorooshMani-NOAA** [comment]
Sorry, I don't know how I made this typo!! Yes, as you pointed out I meant to say `ocsmesh.utils.interpolate`!! I think the error you're getting now is related to the type of the mesh object. Both objects passed to this `interpolate` function must be `jigsawpy.msh_t` type. So you just need to call `interpolate(mesh_s1.msh_t, hfun_msh_t_2)`. 


By the way I'm not sure what exactly you're trying to do here. Do you have bathy data on `mesh_s1` that you'd like to interpolate on `hfun_msh_t_2`?
If you want to interpolate the data from `gen_subdmn.2dm` or `o4-v01-0m_igld85_ocsmesh.2dm` bathy values to your new mesh `mesh_s1` (based on the script you shared earlier) then you need to call `interpolate(size_function_mesh.msh_t, mesh_s1.msh_t)`. In Since you haven't modified the values of the `size_function_mesh`, it should be equal to the values read from the disk, which as I understand should be bathy data. Also please note that the crs of `size_function_mesh` and `mesh_s1` should be the same before calling the interpolate, so you might need to call `ocsmesh.utils.reproject(size_function_mesh.msh_t, mesh_s1.crs)` first

**Comment by melissamattwig** [comment]
No worries at all!

> If you want to interpolate the data from gen_subdmn.2dm or o4-v01-0m_igld85_ocsmesh.2dm bathy values to your new mesh mesh_s1 (based on the script you shared earlier) then you need to call interpolate(size_function_mesh.msh_t, mesh_s1.msh_t)

Yes, this is what I'm trying to do. So I fixed the code and it did not throw an error! I checked the 2dm file that I created from this new mesh, BUT it did not interpolate correctly. It is giving the same depth over the entire mesh. I also doubled checked the original mesh `o4-v01-0m_igld85_ocsmesh.2dm` to make sure it had reasonable depth (z) data and it does. Is there some other characteristic that the mesh I'm interpolating needs to have for it to work?

**Comment by SorooshMani-NOAA** [comment]
Just to make sure I understand correctly, you're doing all above and then in the end:
```python
driver_s1 = ocsmesh.JigsawDriver(genesee_driver_domain, rivers_size_function)
mesh_s1 = driver_s1.run()

ocsmesh.utils.interpolate(size_function_mesh.msh_t, mesh_s1.msh_t)
mesh_s1.write('/path/to/your/output/file.2dm', format='2dm')
```

and the mesh values are not interpolated? If that's the case, usually it's something like the CRS is not the same between the source and target of interpolation or there's a problem with source. Usually there's a possibility that **some** nodes might not have an interpolated value because they fall out of the bounds of the source mesh, but there's no generic requirement for the mesh to interpolate.

You can manually inspect your `size_function_mesh.msh_t.value` and the same for `mesh_s1.msh_t.value`. Or print the `.crs` of both of these mesh objects to make sure they are equal, etc.

**Comment by melissamattwig** [comment]
After confirming that they have the same crs, I realized that the interpolation did work for the most part. The reason it was difficult to see was because there were some nodes in the mesh (it has around 850k nodes or something like that) that had really wacky z data (-99999) so it was throwing off the whole depth plot until I zoomed in on specific areas (I think that is an issue for another thread though). All in all, the original issue I was having with the jigsaw error code is resolved, thank you very much!!

**Comment by SorooshMani-NOAA** [comment]
No problem! Please let me know if you run into any other issues using OCSMesh.
