### ISSUE TITLE
Automate v-grid generation

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/OCSMesh#147]

**Comment by saeed-moghimi-noaa** [comment]
Perhaps connecting to our colleagues from Portugal regarding their work.

**Comment by felicio93** [comment]
INFO:
lsc2 script: [vgrid_lsc2](https://github.com/felicio93/vgrid_lsc2)

Tasks:
1 - Reduce the dependence on pylib
2 - Coordinate implementation under PYSCHISM
3 - ...

**Comment by felicio93** [comment]
I updated the [vgrid_lsc2](https://github.com/felicio93/vgrid_lsc2) notebook.
Now it only uses numpy and pyschism (no pylib dependencies)

**Comment by felicio93** [comment]
Slip the script into functions. Will coordinate with Soroosh on how to proceed.

**Comment by felicio93** [comment]
**Created:** 
set_m_grid(self) # set master grid
set_lsc2_att(self, gr3, crs=None) # set lsc2 attributes
write(self, path, overwrite=False) # write vgrid.in lsc2 file

as part of the Vgrid class (child class LSC2) on PySCHISM.

**The user can now:**
1) create a LSC2 object: 
                                       lsc2_obj = pyschism.mesh.vgrid.LSC2(hsm, nv, h_c, theta_b, theta_f)

2) set a master grid: 
                                       lsc2_obj.set_m_grid()

3) set a lsc2 grid by passing the hgrid: 
                                       lsc2_obj.set_lsc2_att({PATH_TO_gr3})

4) set a lsc2 grid by passing the hgrid: 
                                       lsc2_obj.write({PATH})


**Next:**
Meet with Soroosh to discuss pull request

**Comment by saeed-moghimi-noaa** [comment]
Hi @felicio93 
Please consider doc string and possible additions for read the doc if it applies to pyschism. Thanks

**Comment by felicio93** [comment]
After meeting Soroosh:

Tasks completed:
 1. Changed the name of functions
 2. Added the possibility of passing the hgrid as path to file or Hgrid object
 3. Changed znd, snd, and nlayer to internal variables
 
 Next:
 1. Create test.py
 2. Coordinate pull request with VIMS

**Comment by felicio93** [comment]
@SorooshMani-NOAA,

I made the changes we discussed on our last meetings, including:
1. Change the name of the functions from "set" to "calc"
2. Allow calc_lsc2_att to take either a gr3 file or gr3 object
3. I also added a new function make_m_plot, for allowing quick master grid visualization

I then added test to a preexisting test file (pyschism\tests\_mesh\test_vgrid). I added the following tests:
1. setUp # for setting up a dummy hgrid, and the lsc2 attributes
2. test_LSC2
3. test_calc_m_grid
4. test_make_m_plot
5. test_calc_lsc2_att
6. test_lsc2_write


[vgrid.py](https://github.com/felicio93/pyschism/blob/calc_write_lsc2/pyschism/mesh/vgrid.py)
[test_vgrid.py](https://github.com/felicio93/pyschism/blob/calc_write_lsc2/tests/_mesh/test_vgrid.py)


Please let me know if you think we are ready to include Fei in the discussion and make the pull request.

**Comment by felicio93** [comment]
Pull request initiated: https://github.com/schism-dev/pyschism/pull/127

**Comment by felicio93** [comment]
Pull request accepted by VIMS. @saeed-moghimi-noaa, should we close this ticket?
