### ISSUE TITLE
Ocean side mesh: around islands

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/OCSMesh#150]

**Comment by felicio93** [comment]
**Near Island**

Information from Joseph's "Mesh generation for Eddying and Transitional Regime" (MSCI602) class:

* Particularly challenging is narrow transitional regime between eddying and non-eddying regimes, e.g. near those tiny islands sitting on very steep bottom slope
  * Stick to the ‘simplicity’ rule, and only add auxiliary arcs to enforce proper resolution in deep water
  * You’ll know if you are successful by looking for spurious ‘upwelling’ (very cold water) near islands:
    * If you are not successful in during the Island meshgen you will see this in the SST (upwelling):
    

![Image](https://github.com/noaa-ocs-modeling/OCSMesh/assets/61760479/7f3a1071-d543-4598-a887-5fa643620133)




* Rule of thumb
  * ~3 km resolution at islands: OK   #***Horizontal Resolution >> Vertical Resolution***,  DO NOT OVER-REFINE ISLANDS IF YOU DON'T HAVE TO
  * 1-3 km at islands: probably OK
  * <1 km resolution: you may have a problem if slope is steep, and may need to add auxiliary arcs to enforce coarser resolution in adjacent deep ocean (always avoid high-res in the deep), e.g.:


![Image](https://github.com/noaa-ocs-modeling/OCSMesh/assets/61760479/18e8b1ee-365b-4fb5-8639-84b74d610bbd)


  * Vertical grid (LSC2) can help to some extent, but not a panacea

***Example:***


![Image](https://github.com/noaa-ocs-modeling/OCSMesh/assets/61760479/2444accf-5b76-4eb2-b157-4b2708bd0002)

**Comment by felicio93** [comment]
tagging @feiye-vims in case he has any other requirement

**Comment by felicio93** [comment]
I moved this discussion to #149
