### ISSUE TITLE
GeoPandas 1.0 drops support for shapely<2

### ISSUE THREAD

**Issue by felicio93** [noaa-ocs-modeling/OCSMesh#160]
GeoPandas 1.0 (June 24, 2024) no longer supports shapely<2 and PyGEOS. The only geometry engine that is currently supported is shapely >= 2.

Several functions/methods will have to be updates on OCSMesh.

For now (the latest OCSMesh version 1.5.7) we are fixing geopandas to be <= 0.14.4.

**Comment by SorooshMani-NOAA** [comment]
@felicio93 thanks for documenting this. Do you know which functions need to be updated? See https://github.com/noaa-ocs-modeling/OCSMesh/issues/52 and https://github.com/noaa-ocs-modeling/OCSMesh/pull/82.

**Comment by felicio93** [comment]
From what I have seen the major thing will be to use the function geopandas.GeoSeries.union_all() instead of unary_union. I will keep this ticket updated as I find other things.
