### ISSUE TITLE
Incorrect handling of `str` or `Path` input for collector geom

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/OCSMesh#172]
See:
https://github.com/noaa-ocs-modeling/OCSMesh/blob/680e0f997e6278302f4cd7bcfd3191ca3baa8645/ocsmesh/geom/collector.py#L216-L228

It should have been `raster.clip(...)`

**Comment by felicio93** [comment]
fixed with the latest pull request https://github.com/noaa-ocs-modeling/OCSMesh/pull/174
