### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by TPCollings** [noaa-ocs-modeling/OCSMesh#24]
Hi Soroosh, 

Sorry I've got some more general questions about OCSmesh and didn't know the best way to contact you. I hope this is okay.

Is there any functionality in OCSmesh to allow a review of the CFL number, to ensure the grid won't create numerical diffusion?

Cheers,

Tom

**Comment by SorooshMani-NOAA** [comment]
Hi Tom, right now such a capability does **not** exist. However, I'd like to add new functionalities (where possible) based on the need. 

OCSMesh uses [`Jigasw`](https://github.com/dengwirda/jigsaw)'s Python wrapper as the meshing engine, and as far as I know `Jigsaw` doesn't accept custom error function. So the best way I can think of to add this functionality is to fiddle with the size function. A method can be added to the `hfun` objects to make sure the specified size is within a given bound or criteria. Right now size constraint based on the topobathy exists; it shouldn't be too hard to add one that gets a reference velocity and timestep to constraint based on CFL as well. For example depending on the model being implicit or explicit you'd do something like:
```python
hfun = ...
hfun.add_contours(...)
...
hfun.add_cfl_constraint(cfl_upper=1 , cfl_lower=-np.inf, ref_vel=10, ref_dt=150, rate=0.1)
...
```
which means *after* applying all refinements, it will check the specified sizes and if it falls outside the specified CFL bounds it will modify it and for regions adjacent to the adjusted location it will propagate based on the distance from the adjusted location.

Do you have a specific way of achieving the CFL check in mind? Is what I described above useful for your use case?

**Comment by TPCollings** [comment]
Hi Soroosh, thanks for your quick response. 

That's a good suggestion you've made. I wonder how dependent it would be on the reference velocity and dt values that are chosen. 

Having read the documentation of OceanMesh2d, they deal with the CFL number not by changing the grid size, but by suggesting the timestep for the model run using the minimum current number. This could potentially be an easier solution to changing the mesh itself?

They also also estimate u as a function of sea surface elevation and depth (|u| = ssh/sqrt(g/h)), taking ssh as 2m which is probably suitable for most regions. I've included an image of the documentation as they describe it better than I can . 

Having some form of CFL check would be extremely useful. I'm looking to generate meshes over large basins, so manually estimating the CFL number for selected points isn't really feasible. 





![image](https://user-images.githubusercontent.com/100429378/188925850-dcf1c534-db98-41b0-b2de-7d08fe2f5dcf.png)

**Comment by SorooshMani-NOAA** [comment]
@TPCollings, I think it really depends on what solver you're using and how you want to set it up; for example for implicit solvers we might actually have to be careful for Courant number to remain above 1. In either case, one either has to choose what their Courant number is and what time step they'd like to use, then find the mesh size from it; or already have the mesh size and Courant number and would like to know what time step is suitable.

- For the first functionality it makes sense to have a method that manipulates the *size function* - as described in [this comment](https://github.com/noaa-ocs-modeling/OCSMesh/issues/24#issuecomment-1239353709) - where it gets input η or velocity reference as well as dt and the bound on Courant number.
- For the second functionality it is more sensible to add a method to *mesh* object. So that when you already have a mesh, pass in the bounds on Courant number and get an estimate for dt.

@WPringle I haven't really worked with OceanMesh2D, can you please comment on this? Does what I'm saying make sense based on your experience?

**Comment by TPCollings** [comment]
@SorooshMani-NOAA Yeah I see your point. I'll be using Schism (more specifically PySchism), so I believe the minimum Courant number shouldn't be less than 0.4 for most modelling applications. How long do you think it might take to add the first functionality described above, which involves manipulating the size function?

**Comment by WPringle** [comment]
> @TPCollings, I think it really depends on what solver you're using and how you want to set it up; for example for implicit solvers we might actually have to be careful for Courant number to remain above 1. In either case, one either has to choose what their Courant number is and what time step they'd like to use, then find the mesh size from it; or already have the mesh size and Courant number and would like to know what time step is suitable.
> 
> * For the first functionality it makes sense to have a method that manipulates the _size function_ - as described in [this comment](https://github.com/noaa-ocs-modeling/OCSMesh/issues/24#issuecomment-1239353709) - where it gets input η or velocity reference as well as dt and the bound on Courant number.
> * For the second functionality it is more sensible to add a method to _mesh_ object. So that when you already have a mesh, pass in the bounds on Courant number and get an estimate for dt.
> 
> @WPringle I haven't really worked with OceanMesh2D, can you please comment on this? Does what I'm saying make sense based on your experience?

Yes there are two ways to do it, both we try to do in OM2D. First is try to manipulate the size function beforehand estimating what the Courant number would be based on size function and depth there and what timestep you want to use. This can work OK but often there are still some points that violate the Courant restriction. So we also have the second way of post-processing the mesh based on final Courant number by deleting or adding in new points and locally remeshing. We did add the second for SCHISM type meshes where we want to provide a lower bound on Courant number, and so therefore we try to add in more points, as well as deleting points to make the upper bound on Courant number which is usually more important for ADCIRC.

**Comment by SorooshMani-NOAA** [comment]
@WPringle thanks for your input. I think since Jigsaw doesn't allow for running single iteration of meshing algorithm like Mesh2D does, I'm mostly stuck with just modifying the size function. Then the user can get the best timestep from the mesh when it's generated from the constrained size function.

@TPCollings I might be able to spend time on it towards the end of next week. Do you have an urgent need for this?

**Comment by TPCollings** [comment]
@SorooshMani-NOAA That would be great thanks. There's no super urgency, but it would be great to have it before the end of the month. Cheers!

**Comment by SorooshMani-NOAA** [comment]
@WPringle, I have a technical question. Why is the Courant number calculation in the referenced text from OceanMesh2D calculated with an additional $\sqrt{g H}$? Is this some kind of *corrected* Courant number for shallow water equation?

**Comment by WPringle** [comment]
> @WPringle, I have a technical question. Why is the Courant number calculation in the referenced text from OceanMesh2D calculated with an additional 
> g
> H
> ? Is this some kind of _corrected_ Courant number for shallow water equation?

Yes. Courant number can be calculated from the characteristic velocity: |u| + sqrt(gh). Here, u is the particle velocity which is unknown but from linear wave theory can be approximated as H*sqrt(g/h), where H is wave height. Now here we just assume wave height of 1 m, but that this could be different. However, generally have found this restriction to work pretty well. Now overland we use a 1 m minimum depth (h). In doing so we have 1*sqrt(g/h) = sqrt(gh) = sqrt(g), i.e., a Froude number (=u/sqrt(gh)) of 1 is the restriction. Perhaps a Froude number of two could be a more conservative restriction for overland flow in which case setting H=2 could also work well.

**Comment by WPringle** [comment]
It seems from above text actually we use H=2 m, but in code it is set to 1 m. Maybe we found 2 to be too restrictive..

**Comment by SorooshMani-NOAA** [comment]
Thank you for the information

**Comment by SorooshMani-NOAA** [comment]
I'll close this ticket since the other two created (#25 & #26) are going to cover what was discussed here
