### ISSUE TITLE
Add CFL constraint for size function

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/OCSMesh#25]
Related to requests in #24. 

Examples:
```python
hfun = ...
hfun.add_contours(...)
...
hfun.add_cfl_constraint(cfl_upper=1 , cfl_lower=-np.inf, ref_vel=10, ref_dt=150, rate=0.1)
...
``` 

where instead of `ref_vel` one can use the estimates discussed in the issue referenced at the top

**Comment by SorooshMani-NOAA** [comment]
@TPCollings, can you please get the [`feature/cflconstraint`](https://github.com/noaa-ocs-modeling/OCSMesh/tree/feature/cflconstraint) branch and test the newly added functionality? I added some basic tests, but I didn't really test it on a large model. Please let me know if you see any issues so that I can fix before merging. Thanks!
Please see: https://github.com/noaa-ocs-modeling/OCSMesh/blob/1dfbff4392982d9d2837d7872d4c516cf26f8c0f/ocsmesh/hfun/raster.py#L704-L710 and https://github.com/noaa-ocs-modeling/OCSMesh/blob/1dfbff4392982d9d2837d7872d4c516cf26f8c0f/ocsmesh/hfun/collector.py#L914-L921 for the new methods. Also you can look at the tests added at https://github.com/noaa-ocs-modeling/OCSMesh/blob/1dfbff4392982d9d2837d7872d4c516cf26f8c0f/tests/api/hfun.py#L44-L401

**Comment by SorooshMani-NOAA** [comment]
@WPringle if you have time at some point can you please take a look at the functions implemented here to see if everything seems right for CFL constraint:
https://github.com/noaa-ocs-modeling/OCSMesh/blob/0d6a105bba8ed823df74824588e5fa91e1a63562/ocsmesh/utils.py#L1760-L1918

**Comment by TPCollings** [comment]
Hi @SorooshMani-NOAA, I've got a workshop till friday and am away till Wednesday next week but will do it by the end of next week if that's okay? Thanks again for your help.

Cheers,

Tom

**Comment by SorooshMani-NOAA** [comment]
Hi @TPCollings, there's no rush for merge, please take your time :)

**Comment by SorooshMani-NOAA** [comment]
@TPCollings, I was wondering if you had the chance to test the updates? If not, I can merge them to the `main` branch and you can just test it there whenever you get the chance to.

**Comment by TPCollings** [comment]
Hi Soroosh,

Sorry I still haven't had a chance to test this! Yeah probably best to
merge it and I can let you know if there's an issue. Cheers
---------------------------------------------------------------
*Thomas Collings* | *Fathom™*
Developer | www.fathom.global | @fathom_global
<https://twitter.com/fathom_global>
Square Works, 17-18 Berkeley Square, Clifton, Bristol, UK. BS8 1HB
***@***.***
---------------------------------------------------------------
