### ISSUE TITLE
conda install fails with UnsatisfiableError (traced back to missing arm64/jigsaw conda package)

### ISSUE THREAD

**Issue by platipodium** [noaa-ocs-modeling/OCSMesh#45]
When I follow install instructions:

```
conda env create -f environment.yml -n ocsmesh
conda activate ocsmesh
conda install -y -c conda-forge jigsawpy
```

I get the following error on the last command (install jigsaw)

```
❯ conda install -y -c conda-forge jigsawpy
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by SorooshMani-NOAA** [comment]
@platipodium, this is interesting. I tried creating the environment using both `conda` and `mamba` to see if it makes any difference (it does **not**!), but in any case I got the environment without any errors. Is it possible that since probably conda is using a different mirror, it has different packages available on your side?

One thing you can try that might work is to modify `python` to be version `3.9` and see if it works. Also to avoid time consuming environment builds, you can install `mamba` and then try creating the environment using `mamba`

**Comment by platipodium** [comment]
I created a new python3.9 env with `mamba create -n ocsmesh -f environment.yml; conda activate ocsmesh` (after changing the python dependency to 3.9), still get an error (but different message)

```
 mamba install -y -c conda-forge jigsawpy
...
Encountered problems while solving:
  - nothing provides jigsaw >=0.9.12 needed by jigsawpy-0.2.1-py_0
```

Now we're talking!  As I am on M1 architecture, the jigsawpy is not provided :=(

**Comment by SorooshMani-NOAA** [comment]
Oh, I see ... you can then just install jigsawpy either from Jigsaw's own repo or by calling `python setup.py install_jigsaw` in OCSMesh repo which downloads, compiles and installs Jigsaw in your env.

**Comment by platipodium** [comment]
Thx, tried but was stopped by #47

**Comment by SorooshMani-NOAA** [comment]
This doesn't look good! Have you tried compiling/installing directly from Jigsawpy repo (please)? https://github.com/dengwirda/jigsaw-python

**Comment by platipodium** [comment]
Haven't tried compiling from repo yet.  But, of course #47 needs to be fixed anyhow.  I'll report on progress later

**Comment by platipodium** [comment]
Manual installation of jigsawpy from https://github.com/dengwirda/jigsaw-python works for me.
