### ISSUE TITLE
Defining boundaries manually

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/OCSMesh#59]
### Discussed in https://github.com/noaa-ocs-modeling/OCSMesh/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **acroucher** January 19, 2023</sup>
The `mesh.boundaries.auto_generate()` function seems to do an OK job of detecting the open ocean boundary (with some nodes possibly omitted at the coastal ends -  if the threshold is increased to pick them up, it starts identifying spurious open boundaries on land, I guess just an inevitable limitation of trying to identify boundaries solely based on elevation).

I will also need to define some open boundaries for e.g. river inputs, and so I probably need to be able to define them a bit more manually.

The user guide states that "To preserve the boundary type accuracy it is possible to programmatically force some
nodes to be on land or in the ocean. However, this is outside the scope of this document." So, how is this done?</div>

Provide a way of assigning node boundary type based on intersection of nodes with an input polygon

**Comment by SorooshMani-NOAA** [comment]
Currently in OCSMesh the specified boundary values (for grd output) is stored in `Boundaries` class defined in `ocsmesh/mesh/mesh.py`. This objects stores the boundary data in two formats simultaneously:
1. `_data`: storing a dictionary of boundaries in the form of `{ boundary_type_id: { boundary_number: [ boundary_vert1, ... ] }`
2. Cached `GeoDataFrame` return values separately created for `ocean`, `land` and `interior`. The `GeoDataFrame` objects have the following columns: 
   ``` 
       'id': <boundary number>,
       'ibtype': <boundary type id>,
       'index_id': <boundary node id list>,
       'indexes": <boundary node index list>,
       'geometry': <LineString of the boundary>
    ```
Both of theses need to be properly updated if manual specification is added.
Right now the only way to set the boundaries is to use `auto_generate` method of `Boundaries` object which based on the value of mesh at each node, (i.e. `mesh.msh_t.value`) assigns _"land"_ or _"ocean"_ for external boundaries, and then assigned _"internal"_ for all internal boundaries.

**Comment by SorooshMani-NOAA** [comment]
There are a couple of things that must be noted here:
- For internal boundaries (i.e. islands) it doesn't make sense to be able to assign boundary type
- There's no internal mechanism right now to check whether all the boundaries are assigned
- It should be decided what would happen if the user assigns a boundary; should the rest be auto-assigned or not? Should there be option?

Also in terms of API, is it enough to have the following:
- `set_ocean(region)`
- `set_land(region)`

or more flexibility is needed? For example more arguments to set the rest to the opposite boundary type when setting a specific region, or to set the inverse of the input region to be of specific boundary type, e.g.:
- `set_land(region, rest_is_ocean=False)`
or
- `set_land(region, inverse=False)`

**Comment by SorooshMani-NOAA** [comment]
@acroucher do you have any preferences related to [the comment above](https://github.com/noaa-ocs-modeling/OCSMesh/issues/59#issuecomment-1424447705), for the API?

**Comment by acroucher** [comment]
I think for myself all I want is to be able to tweak the boundaries set by `auto_generate()`, and add boundaries for e.g. river inputs. So simple `set_ocean()` and `set_land()` which didn't try to do anything too clever would be ok - i.e. they wouldn't need to auto-assign other boundaries. But perhaps `set_ocean()` would be better named something like `set_open()` for use in e.g. the river input case?

**Comment by SorooshMani-NOAA** [comment]
@acroucher, sorry for the long delay, but now the functionality seems to be ready. Can you please test and see if it meets your requirement? You can use `set_open` or `set_land` and pass in a `shapely.geometry.Polygon` or `MultiPolygon` to specify boundary edges.

Note that BC type of all the boundary edges connected to the vertices that fall within the polygon are specified by the called function.

**Comment by acroucher** [comment]
I just tested this, and it does seem to do what I need - thanks a lot! I have only tested `set_open()` as that's the one I needed for defining river boundaries.

If I call `set_open()` multiple times to define several rivers, is it guaranteed that the boundaries in the resulting gr3 file will be in the same order? This is important for setting the correct boundary conditions for each river. For the example I tried it seems to be the case, but I just wanted to check if this is guaranteed.

**Comment by acroucher** [comment]
One thing I noticed in the gr3 file is that the comments on the boundaries refer to "ocean" and "non-ocean" boundaries, and my river boundaries are labelled "ocean" boundaries, which isn't quite right... perhaps it would be better to call them "open" and "land" boundaries instead (as in the [SCHISM docs](https://schism-dev.github.io/schism/master/input-output/hgrid.html))?

**Comment by SorooshMani-NOAA** [comment]
Thanks for testing!

> is it guaranteed that the boundaries ... same order?

It's not explicitly guaranteed by the code, but I can add a test to make sure it's always so. Just to make sure I understand correctly, are you talking about the order of nodes in each boundary, or the order of the boundary segments, e.g. open boundary 1, open boundary 2, etc.?

> perhaps it would be better to call them ...

Sure, that makes sense. I updated the names to match SCHISM docs

**Comment by acroucher** [comment]
> Just to make sure I understand correctly, are you talking about the order of nodes in each boundary, or the order of the boundary segments, e.g. open boundary 1, open boundary 2, etc.?

The order of the boundary segments. At present, in my case, it looks like ocean_boundary_0 is the actual ocean boundary, ocean_boundary_1 is the first river (i.e. defined by the first call to `set_open()`), ocean_boundary_2 is the second river, etc.

If that is always the case it would be great. The ordering of open boundaries is used in the SCHISM input `bctides.in` and `flux.th` etc. for setting up river inflows.

**Comment by SorooshMani-NOAA** [comment]
Right now the existing guarantee is the following (based on how I number the boundaries **and** the fact that Python dictionaries order is preserved when items are inserted one by one):

- Every time a new boundary is set, that segment is separated from the rest and becomes a boundary at the end of the "boundaries list". The rest of the boundary remains in the order-location, however if the rest is actually segmented in two by the new boundary, then the second segment is also separated and added to the end, before the specified new boundary. e.g. if we have nodes 1, 2, ..., 10 as ocean and I set 2,3,4,5 to ocean then:
   + The boundary is segmented into 3: 1, 2 -> open boundary with same ID as before (same location)
   + At the end of the rest of the boundaries of the whole mesh a new 5, 6, 7, 8, 9, 10 open boundary is created
   + Then a 2, 3, 4, 5 segment is created and is added again at the end, after the one from previous step
- Multi segment boundary specification should also be handled without an issue (e.g. non convex shape passed to set a boundary on a straight line)
- In general when a boundary is specified, whether ocean or land, first OCSMesh resolves the conflicts with the old boundary and segments the old boundaries (whether ocean or land). The new segments of the old boundary are added at the end. Then the new boundary segment(s) are added after those segmented boundaries:
see https://github.com/noaa-ocs-modeling/OCSMesh/blob/3f145ca809c24ab0c784e0b177a4326e6d609ba6/ocsmesh/mesh/mesh.py#L1920-L1924
  

I can add a simple test where I specify multiple boundaries, and then assert that order is preserved, but I can't think of a better test to have a stronger guarantee.

**Update**
To clarify, the current code does guarantee the order of segments, but **not** order of nodes within segments

**Comment by acroucher** [comment]
I'm slightly nervous if it relies on the order of items in dictionaries, as I seem to recall getting a bit burnt by that before! I thought there were basically no guarantees about the order of items in Python dictionaries, unless that has changed.

However, it seems to be ok for the mesh I tested.

Slightly separate issue - out of curiosity (I don't plan on doing this), if you set two boundaries open and they were in fact contiguous (i.e. the end of one was the start of the other), would you still get two separate open boundaries or would it merge them into one?

**Comment by SorooshMani-NOAA** [comment]
> I'm slightly nervous if it relies on the order of items in dictionaries, as I seem to recall getting a bit burnt by that before! I thought there were basically no guarantees about the order of items in Python dictionaries, unless that has changed.

I'm not very comfortable with this either, due to the history, but it seems we should be fine; see: https://medium.com/junior-dev/python-dictionaries-are-ordered-now-but-how-and-why-5d5a40ee327f

Right now even if two specified "open" (or two specified "land") boundaries are contiguous, they are still stored/written separately. I'm not sure if this is going to cause issues or just adds more overhead to SCHISM (or other models') accounting of boundaries. 

@josephzhang8 is this going to be an issue? Let's say we have a single contiguous open boundary on the ocean side; is it OK if we break it in two and write the pieces in two separate boundaries (with one shared node between the two)?

**Comment by acroucher** [comment]
Actually the reason this came to mind was that I wondered if I could use `set_open()` to adjust the ends of my open ocean boundary. When I use `auto_generate()` it typically creates an open ocean boundary that stops short of the actual coast, where the elevation rises above the specified threshold (and I can't set the threshold higher because then I get spurious bits of open boundary popping up on other bits of the coast).

So I wondered if I could use `set_open()` to correct the open ocean boundary at the ends, but I suspect then I'll get multiple open ocean boundaries. I'm not so worried about it creating additional overheads for SCHISM but more just that I'd have to set BCs on multiple boundaries in `bctides.in` and `flux.th`, which is a bit of a pain.

The alternative is just to not worry if the open ocean boundary doesn't quite extend all the way to the coast, I guess. In your experience is that actually a problem?

**Comment by SorooshMani-NOAA** [comment]
I see. I don't think I'm the best person to ask about the implication of not extending to coast, but I think it shouldn't have huge implications, unless it's very close to a high-res region of the mesh where you're interested in capturing certain phenomena.

@cuill, do you have any recommendations?

By the way @acroucher, I'm not sure how your setup is, but using [`pyschism`](https://github.com/schism-dev/pyschism) might help with the boundary conditions and flux time histories.

In any case, I'll see if it's not too much change I can add a flag to merge if boundaries are of the same type.

**Comment by acroucher** [comment]
Thanks. No, I don't want to have ocean boundaries close to anything important. And yes, I have been experimenting with ``pyschism``, particularly for generating the atmospheric forcing.

**Comment by josephzhang8** [comment]
All-

SCHISM allows dove-tailed open boundary segments.


Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)
SCHISM web: http://ccrm.vims.edu/schism/

**Comment by SorooshMani-NOAA** [comment]
Thanks @josephzhang8!

@acroucher, I added some code to merge similar boundaries. I ran into an issue with keeping order after that, but added some more code to keep the order as well; so all should work as discussed and expected. Can you please test the branch again and let me know if you notice anything?

To merge the specified boundary with the old existing ones you need to pass `merge=True`, by default it's `False`. e.g.:
```python
mesh_obj.boundaries.set_open(region=myshape, merge=True)
```

One **important** thing: In general if you specify a boundary that fully removes an existing one (with or without merge), the new boundary will go to the end and the completely removed boundary is popped (so the new boundary doesn't take the place of the old -removed- boundary in terms of order). With this one, I don't think there's any easy way around it!

I'm planning to merge this branch some time next week. I'd appreciate some feedback if you have time. Have a good weekend!

**Comment by SorooshMani-NOAA** [comment]
A note from SCHISM documentation at https://schism-dev.github.io/schism/master/input-output/hgrid.html:
> Although not required, we recommend you follow the following convention when generating the boundary segments. For the exterior boundary (open+land), go in counter-clockwise direction.

Right now this is **not** enforced in OCSMesh (#65)

**Comment by josephzhang8** [comment]
This is fine. Convention is useful when you have a lot of segments and keep the user sane.

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by SorooshMani-NOAA** [comment]
@josephzhang8 just a quick follow up question: The documentation doesn't seem to say anything about the internal (island) boundary order. I'm assuming since external is ccw, islands should be cw, right? If there's such convention, is it mandatory for islands?

**Comment by josephzhang8** [comment]
Correct, we usually use cw for islands. It's not mandatory.

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by acroucher** [comment]
I just tried using the new ``merge`` parameter and I'm getting an error message:

```python
>>> p = Polygon([[174.60829,-36.07754], [174.60622, -36.09822], [174.60823, -36.09899], [174.61242, -36.08162]])
>>> m.boundaries.set_open(p, merge = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/acro018/software/shallow_water/ocsmesh/ocsmesh/mesh/mesh.py", line 1912, in set_open
    self._set_region(region, None, merge)
  File "/home/acro018/software/shallow_water/ocsmesh/ocsmesh/mesh/mesh.py", line 1943, in _set_region
    boundaries = self._resolve_assignment_conflict(edge_list_idx, boundaries)
  File "/home/acro018/software/shallow_water/ocsmesh/ocsmesh/mesh/mesh.py", line 2020, in _resolve_assignment_conflict
    prop = boundaries[tp_id][bd_id]['properties']
KeyError: 'properties'
```
In fact I get the same result if I omit the ``merge`` parameter. Am I doing something wrong?

**Comment by SorooshMani-NOAA** [comment]
@acroucher thanks for catching this error. You're use is totally fine. The issue is when OCSMesh reads `.gr3` or `.14` file with boundaries, it doesn't construct the full structure assumed by the boundary handler code. I'll fix this. I also noticed an issue when a mesh with no boundary is read in (either `2dm` or `14`).

All of my tests had an auto boundary generation so I didn't catch either of these!

**Comment by SorooshMani-NOAA** [comment]
As a side note, since "island" boundaries cannot be specified (all mesh holes are islands), I didn't actually add a `set_island` method. But this means if islands are not specified either _prior_ to importing the mesh or using `auto_generate()`, then there's no way to manually specify them.

Still, I'm not sure if it makes sense to add `set_island` to the code. Maybe I can just add `find_islands` which would be the same as `auto_generate`, but for only finding and setting island boundaries.

What do you think @acroucher?

**Comment by josephzhang8** [comment]
Hi Soroosh:

In general users may want to specify open bnd on islands as well. This is rare but it'd be good to allow that.

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by SorooshMani-NOAA** [comment]
Oh, I didn't know about that. Thanks for the information. I created a separate ticket (#66) to address this, so that we can move forward with this merge #62 some time later this week.

**Comment by SorooshMani-NOAA** [comment]
@acroucher I have made the changes for the bugfix and finding islands discussed above (excluding open bndry on islands). Please let me know if you run into any more issues. Thanks!

**Comment by acroucher** [comment]
Thanks, I have tested using the merge option of ``set_open()``  to set some of the shallow nodes on my boundary open, and it successfully merged them into the existing open boundary (so there is still only one open boundary).

However if I call ``auto_generate()`` first (before ``set_open()``), I'm getting an error in there now:

```python
Traceback (most recent call last):
  File "mesh.py", line 142, in <module>
    mesh.boundaries.auto_generate(-16)
  File "/home/acro018/software/shallow_water/ocsmesh/ocsmesh/mesh/mesh.py", line 1882, in auto_generate
    for ext_ring in self.nodeidxlist['exterior']:
  File "/home/acro018/software/shallow_water/ocsmesh/ocsmesh/mesh/mesh.py", line 1610, in nodeidxlist
    if not ring.geometry.is_ccw:
AttributeError: 'LineString' object has no attribute 'is_ccw'

```

**Comment by SorooshMani-NOAA** [comment]
@acroucher, it's strange. I actually got this error in my automated tests on GitHub workflow, then I removed `pygeos` from my environment and it fixed the issue! I couldn't reproduce it locally to see what is going on. If it is feasible, can you please remove `pygeos` from your OCSMesh environment and see if the issue is resolved or not?

In the meantime I investigate this a bit more on my local machine. After switching to Shapely `2` (whenever that happens) we shouldn't have any of these issues #52. The downside of uninstalling `pygeos` while we're still on pre-`2` Shapely is slower GEOS operations.

**Update**
I was able to reproduce locally! The issue is `pygeos` compatibility with `shapely`. If you get a warning like below when you run OCSMesh, it means that the `shapely` you have installed is not fully compatible with your `pygeos`. This seems to result in the the boundary being translated into `LineString` instead of `LinearRing` when going back and forth between `shapely` and `geopandas` (which uses `pygeos` when available):
```
UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
```

For example see the difference below where one environment has incompatible `pygeos` and the other doesn't:
```ipython
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import geopandas as gpd

In [2]: from shapely import geometry

In [3]: bx = geometry.box(-78, 33, -73, 38)

In [4]: gdf = gpd.GeoDataFrame(geometry=[bx.exterior])

In [5]: gdf.iloc[0].geometry
Out[5]: <shapely.geometry.polygon.LinearRing at 0x7f7de4e31f00>
```

as opposed to

```ipython
(2023)$ ipython
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import geopandas as gpd
/home/smani/miniconda3/envs/ocsmeshpip/lib/python3.9/site-packages/geopandas/_compat.py:123: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

In [2]: from shapely import geometry

In [3]: bx = geometry.box(-78, 33, -73, 38)

In [4]: gdf = gpd.GeoDataFrame(geometry=[bx.exterior])

In [5]: gdf.iloc[0].geometry
Out[5]: <shapely.geometry.linestring.LineString at 0x7f4ec86cdb80>
```

In both cases above `pygeos` version `0.14` is installed.

**Comment by SorooshMani-NOAA** [comment]
@acroucher I added a minor change to fix this incompatibility issue. Please let me know if the latest code works for you as it is, even if you don't remove `pygeos`. Thanks a lot for your feedback!

**Comment by acroucher** [comment]
Thanks, yes, that has fixed it!

(I do get that warning about PyGEOS - I have never figured out a way to sort it out.)

**Comment by SorooshMani-NOAA** [comment]
Thanks for testing!

> (I do get that warning about PyGEOS - I have never figured out a way to sort it out.)

I don't have a good solution either. I know if I use `conda` to create my environment, it will automatically pick up compatible versions of `shapely` and `pygeos`, but I don't know how to enforce it with `pip`. In any case after `shapely>=2` there won't be any `pygeos`, so there won't be an incompatibility issue like this!

**Comment by saeed-moghimi-noaa** [comment]
Thanks @SorooshMani-NOAA . Please archive this item.
