### ISSUE TITLE
Dense mesh on open boundary when using clipped rasters

### ISSUE THREAD

**Issue by TPCollings** [noaa-ocs-modeling/OCSMesh#72]
Hi there,

I've been generating some meshes of the Gulf of Mexico, and am having issues with the size functions.

If I generate the mesh using the original gebco rasters, they generate as expected, with small elements on the coastline, and large elements on the open boundary in deep water. 

However, if I clip and merge the gebco raster in Qgis, so that they are smaller (but still extend outside of the domain of the mesh), I get a refined mesh on the whole boarder (see attached image).

Does anyone have any idea why this is happening? Is it something to do with the raster metadata?

Cheers,

Tom
![new_orleans06_480](https://user-images.githubusercontent.com/100429378/228272720-5e1fde0f-d257-4c27-8681-affd5ecea056.png)

**Comment by SorooshMani-NOAA** [comment]
@TPCollings if the inputs for your meshing (clipped rasters, domain shape, your script) is not too large, can you please zip and attach them to the ticket so I can try and see if I can find why this is happening?

I know sometimes passing base shape to the size function collector causes problem at the edges, maybe that's the issue. But the strange thing is that you don't have this issue if you don't merge rasters, right? Maybe after merging, the merge raster's pixels align such that the hfun-collector clipping causes this problem vs when you use the original rasters.

**Comment by TPCollings** [comment]
Hi Soroosh,

So I've just now been able to solve it by removing the base_shape from the hfun-collector and specifying the crs of the merged raster when using the Raster functions. Do you still want to check it?

Cheers,

Tom

**Comment by SorooshMani-NOAA** [comment]
Yes, if possible it's good to have the whole issue (files and all) documented here. I've seen this issue here and there before, but never pinned it down to fix it. Since you already see the issue and have a demonstrating small test case, it's good to have it completely in one place. Thanks!

**Comment by TPCollings** [comment]
Hi Soroosh,

As mad as it sounds I now can't recreate the bug from my original scripts. I literally don't know how or why, but I've tried all morning to no avail. Sorry!

**Comment by SorooshMani-NOAA** [comment]
Yeah, that's the issue with some bug!! No problem! At least there's a ticket for it now

**Comment by SorooshMani-NOAA** [comment]
Since this seems to be a stale issue I close it for now
