### ISSUE TITLE
Error in hfun.add_feature()

### ISSUE THREAD

**Issue by TPCollings** [noaa-ocs-modeling/OCSMesh#75]
As a work around to issue #74 I am trying to refine the shelf edge using either a manually drawn line feature or a multiline feature created using a contour from a slope analysis of the DEM. 

Both times the kernel crashes when trying to create the mesh using hfun.msh_t()

I'm pretty sure I'm using the add_feature function correctly so not sure why it's bugging out. Might be an error in the code?

Cheers,

Tom

**Comment by SorooshMani-NOAA** [comment]
Would it be possible for you to provide more information? Like error code you get from Jigsaw (if any) or Python traceback. Having an excerpt of the script you're running could also help with the debugging. Thanks!

**Comment by TPCollings** [comment]
An update on this - it is related to updating ocsmesh to the latest version. I think it could be related to geopandas? When I try to open a shapefile containing the domain to mesh, the kernel crashes. I will try updating geopandas and if that doesn't work I will create a new environment from scratch

**Comment by TPCollings** [comment]
Updating the packages in the environment didn't work so I'll try recreating the env and see if that works

**Comment by TPCollings** [comment]
Rebuilding the environment has solved this issue. I guess there was a dependency issue.
