### ISSUE TITLE
River meshing for Alaska region

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/OCSMesh#88]
In parallel to #50 we'd like to explore river meshing in Alaska region using the same tools. 

As suggested by @saeed-moghimi-noaa and @BahramKhazaei-NOAA we'd like to start with a regional mesh in that domain, e.g. Cook Inlet, and use existing DEMs to extract the river using https://github.com/schism-dev/RiverMeshTools and embed it either in a subsetted Alaska mesh or a mesh generated for the region from scratch.

The data will be shared internally, but we'll discuss the outcomes and suggestions here.

**Comment by BahramKhazaei-NOAA** [comment]
@SorooshMani-NOAA thanks for starting the issue. Please look at the comment on Mar 21 in this [issue](https://github.com/orgs/noaa-ocs-modeling/projects/8/views/1?pane=issue&itemId=23532027) for links to:
1. Alaska DEMs
2. ADCIRC domain files that gives the current domain boundaries.

**Comment by SorooshMani-NOAA** [comment]
It seems that for now this item is abandoned. So I close this as not planned.
