### ISSUE TITLE
Hfun.add_contour fails with latest Shapely

### ISSUE THREAD

**Issue by SanderHulst** [noaa-ocs-modeling/OCSMesh#93]
Dear developers,

First of all, thank you for this package!

There seems to an issue with hfrun.add_contours which I believe is caused by a new exception in shapely.

I have the shinnecock example as a test case in our grid creation library but feed it only with clipped gebco 2020 data so that I do not have to store a lot of binary data in our gitlab repository.

When I try to add contours, an exception is raised: `shapely.errors.GEOSException: IllegalArgumentException: point array must contain 0 or >1 elements` It is apparently possible to have contours of one point.

In https://github.com/noaa-ocs-modeling/OCSMesh/blob/main/ocsmesh/raster.py#L1395 a ValueError is caught, but not the GEOSException.

The issue can be solved by either adding the GEOSException. I can fork and send a PR if you want.

With best regards,
Sander

**Comment by SanderHulst** [comment]
https://github.com/noaa-ocs-modeling/OCSMesh/pull/94

**Comment by SanderHulst** [comment]
[pip_versions.txt](https://github.com/noaa-ocs-modeling/OCSMesh/files/11815048/pip_versions.txt)

**Comment by SorooshMani-NOAA** [comment]
Closed by #94
