### ISSUE TITLE
Mesh.interpolate() using another mesh rather than a raster

### ISSUE THREAD

**Issue by TPCollings** [noaa-ocs-modeling/OCSMesh#98]
Hi there,

Is it possible to interpolate the depths from another mesh rather than a raster? I've made some manual edits to some depths on an older mesh, and I want to include them in a new mesh, but can't make the edits in the same way. Is there some work around I might be able to do by using the mesh depths to edit the original raster?

Cheers,

Tom

**Comment by SorooshMani-NOAA** [comment]
Hi @TPCollings, yes you can interpolate mesh on mesh. Although the functionality is **not** exposed through the `Mesh` objects, but through a `utils` function. See:

https://github.com/noaa-ocs-modeling/OCSMesh/blob/8e2d43e4e3d74f04780dec9913debe7811c4e779/ocsmesh/utils.py#L1283-L1292

So if you have two mesh objects, one with desired elevations and another with desired node/cell formation, then you can do something like the following:

```python
from copy import deepcopy
import ocsmesh

mesh_w_good_elev = ocsmesh.Mesh.open('path/to/this/mesh', ...)
mesh_w_good_cell = ocsmesh.Mesh.open('path/to/that/mesh', ...)

m_internal_elev = deepcopy(mesh_w_good_elev.msh_t)
m_internal_cell = deepcopy(mesh_w_good_cell.msh_t)
ocsmesh.utils.interpolate(src=m_internal_elev, dst=m_internal_cell, ...)

# Now m_internal_cell also has "good values"
mesh_w_good_everything = ocsmesh.Mesh(m_internal_cell)
mesh_w_good_everything.write('path/to/interpolated/mesh', ...)
```

Actually since the `interpolate` function modifies the `jigsaw_msh_t` object in place you can skip some of the steps (e.g. avoid `deepcopy`) outlined above, but I'm just writing them for the sake of clarity.

Please let me know if this helps.

**Comment by TPCollings** [comment]
Hi Soroosh,

Thanks for you help, that has worked but it hasn't given me the desired result. The mesh I'm interpolating to is bigger than the old mesh, and so there are lots of areas of no data that fall outside of the interpolation space. Can you think of another method that might work better? 

Basically I've got 1 mesh which goes up to the 0m contour, in which I've lowered all elevations greater than -0.5m to -0.5m, to ensure water can flow through the channels etc. 

I've then created a new mesh which goes up to the 1m contour, so as to capture the tidal/mud flats in the area which are important for propagating water during storm surges. I'd like to merge the two meshes so that all the details from the first mesh (i.e. all elevations over -0.5m lowered to -0.5m so water can move around freely) are combined with the tidal/mud flats from the second mesh. 

Any ideas gratefully appreciated.

**Comment by SorooshMani-NOAA** [comment]
OK, so here is my understanding of your requirement:
- You have an old mesh that extends up to coastline (`0`m) which has all elevations above (`-0.5`m) set to `-0.5`
- You have a new mesh that extends up to `1`m that has correct elevation values (at least from `0`m to `1`m)
- You'd like your new mesh elevations to be modified such that
   + All its nodes that fall **within** the multipolygon of the old mesh get their elevation interpolated from the old mesh
   + All its nodes that fall **within** the region of the old mesh that has `-0.5` value have elevations equal to `-0.5`
   + All the nodes that fall **out of** the multipolygon of the old mesh have their values from the original new mesh (or be interpolated form rasters?)

If that's the case my suggestion is to do masking and setting values at `jigsaw_msh_t` level, which is basically a `numpy` array with special `dtype`. OCSMesh provides some utility functions to help with that such as:
https://github.com/noaa-ocs-modeling/OCSMesh/blob/8e2d43e4e3d74f04780dec9913debe7811c4e779/ocsmesh/utils.py#L193
https://github.com/noaa-ocs-modeling/OCSMesh/blob/8e2d43e4e3d74f04780dec9913debe7811c4e779/ocsmesh/utils.py#L781-L786
https://github.com/noaa-ocs-modeling/OCSMesh/blob/8e2d43e4e3d74f04780dec9913debe7811c4e779/ocsmesh/utils.py#L1283
All of which work on `jigsaw_msh_t` objects. Then these could be used along with `numpy` slicing and masking to get the desired results:
```python
new_msht = newmesh_obj.msh_t
old_msht = oldmesh_obj.msh_t

old_shape = ocsmesh.utils.get_mesh_polygons(old_msht)
vert_idx = ocsmesh.utils.get_verts_in_shape(new_msht, old_shape)
new_msht.value[vert_idx] = ...
```

Or something along these lines (including interpolation, etc.)

**Comment by TPCollings** [comment]
Thanks Soroosh, will give it a go

**Comment by SorooshMani-NOAA** [comment]
@TPCollings any luck with using OCSMesh for this specific case?

**Comment by SorooshMani-NOAA** [comment]
I'm closing this ticket assuming either the issue was resolved or is no longer relevant. Please feel free to reopen it if needed.
